[package]
name = "hexpds_auth_jwt_internal"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "hexpds_auth_jwt_internal"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
jwt-simple = "0.12.9"
serde_json = "1.0"
rustler = "0.33.0"
cmake = "0.1.50"
