[package]
name = "hipdster_auth_jwt_internal"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "hipdster_auth_jwt_internal"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.32.1"
